apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edge-proxy.fullname" . }}
  labels:
    {{- include "edge-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "edge-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "edge-proxy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: edge-proxy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
